// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFT_GkmYPIBxTUhu__rt6rO6F3y1zS3o0',
    appId: '1:386394522334:web:550fe24975ddaf9dcff84f',
    messagingSenderId: '386394522334',
    projectId: 'rento-c192e',
    authDomain: 'rento-c192e.firebaseapp.com',
    storageBucket: 'rento-c192e.appspot.com',
    measurementId: 'G-TW9ZXVPHGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVo--8vC9zJW-x_vp-IuMLYHrMIR4A4_Y',
    appId: '1:386394522334:android:4375592bccee4a75cff84f',
    messagingSenderId: '386394522334',
    projectId: 'rento-c192e',
    storageBucket: 'rento-c192e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Z1k98xOx9HeR2BHZVwvNFLONGrII2sM',
    appId: '1:386394522334:ios:a365a8653fd7b9facff84f',
    messagingSenderId: '386394522334',
    projectId: 'rento-c192e',
    storageBucket: 'rento-c192e.appspot.com',
    iosClientId:
        '386394522334-s4e6dolrm6c0mk4k5lr4polg9uga38ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.rento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Z1k98xOx9HeR2BHZVwvNFLONGrII2sM',
    appId: '1:386394522334:ios:a365a8653fd7b9facff84f',
    messagingSenderId: '386394522334',
    projectId: 'rento-c192e',
    storageBucket: 'rento-c192e.appspot.com',
    iosClientId:
        '386394522334-s4e6dolrm6c0mk4k5lr4polg9uga38ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.rento',
  );
}
